name: 'Mark all Issues as Stale Once'

on: push
  # workflow_dispatch:  # Manuell starten

jobs:
  stale-initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This Issue is marked as stale'
          stale-issue-label: 'stale'
          days-before-issue-stale: -1  
          days-before-issue-close: -1 
          operations-per-run: 1000
          remove-issue-stale-when-updated: true

