name: Remove all 'Stale' labels from issues

on:
  workflow_dispatch:  # manuell starten

jobs:
  remove-stale-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        # if: ${{ startsWith(github.event.comment.body, '/remove-labels') }}
        with:
          labels: stale
