name: Sync Actions

on:
  # push: 
  #   branches: [ main ]
  #   paths:
  #     - '.github/workflows/**'
  workflow_dispatch:
  
   

jobs:
  replicate:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Push Action to repos
        uses: derberg/manage-files-in-multiple-repositories@v2
   
        with:
          github_token: ${{ secrets.MULTI_ACCESS_TOKEN }} # PAT mit Schreibrechten auf alle Ziel-Repos
          patterns_to_include: .github/workflows/MarkAndCloseStaleIssuesPush.yml
          patterns_to_ignore: .github/workflows/SyncActions.yml
          topics_to_include: icinga
          # destination: '.github/workflows'
          committer_username: Sync-Action
          commit_message: "ci: update workflow action for stale issues"
          
      - name: Debug Token Access
        run: |
          echo "Testing repository access..."
          curl -H "Authorization: token ${{ secrets.MULTI_ACCESS_TOKEN }}" \
                 https://api.github.com/user/repos?per_page=1
