name: "Sync Actions"

on:
  push: 
    branches: [ main ]
  workflow_dispatch: {}
  
   

jobs:
  replicate_changes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Manage Files in Multiple Repositories
        uses: derberg/manage-files-in-multiple-repositories@v2
      # - uses: derberg/manage-files-in-multiple-repositories@v2
        with:
          github_token: ${{ Multi-Repo-Workflow-Token }} # PAT mit Schreibrechten auf alle Ziel-Repos
          patterns_to_include: '.github/workflows'
          patterns_to_ignore: '.github/workflows/SyncActions.yml'
          # topics_to_include: icinga
          destination: '.github/workflows'
          commit_message: "ci: update workflow action for stale issues"
          bot_branch_name: bot/update-files-from-global-repo
